name: windows_ocr
description: Windows OCR.
version: 0.0.1
homepage: https://github.com/hamdikahloun/windows_ocr

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.12
  xml:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      windows:
        pluginClass: WindowsOcrPlugin
